[package]
name = "oracle"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
near-sdk.workspace = true
lib = { path = "../../lib" }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
